user-server:
  port: 50051
post-server:
  port: 50052
processor-server:
  port: 50053
comment-server:
  port: 50054
queue:
  brokers:
    - "kafka-gcp-europewest1.streaming.datastax.com:9093"
  topic: users-topic
  group_id: processor-service-group
  username: witty-tenant

database:
  username: token
  token: token
  path: ./secure-connect.zip
  keyspace: threads_keyspace
