user_server:
  port: 500051
processor-server:
  port: 500052
queue:
  brokers:
    - "127.0.0.1:9042"
    - "127.0.0.1:9043"
    - "127.0.0.1:9044"
  topic: outbox
  group_id: processor-service

database:
  username: token
  token: token
  path: ./secure-connect.zip
  keyspace: threads_keyspace